plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.rootlauncher'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.rootlauncher"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.activity:activity:1.7.2' // 必须加这一行，否则文件选择器会报错
    implementation 'com.google.android.material:material:1.9.0'
}
